server:
  port: 9999
magic-api:
  web: /magic/web
  resource:
    location: ${MAGIC_LOCATION_PATH}
  show-url: false
  show-sql: true
  response-code:
    success: 0
    invalid: 1
    exception: -1
  page:
    size: pageSize
    page: page
    default-page: 1
    default-size: 10
  security:
    username: ${SECURITY_USERNAME}
    password: ${SECURITY_PASSWORD}


spring:
  datasource:
    url: ${MYSQL_EN_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=${MYSQL_EN_TZ}
    username: ${MYSQL_EN_USERNAME}
    password: ${MYSQL_EN_PASSWORD}