erupt-app:
  verifyCodeCount: 2
  pwdTransferEncrypt: true
  locales: [ "zh-CN", "en-US"]
erupt:
  csrfInspect: false
  redisSession: false
# need to replace
  uploadPath: /opt/erupt-attachment
#  uploadPath: /Users/rivery/Desktop/projects/new-website/attachments
  keepUploadFileName: false
  upms.expireTimeByLogin: 600
  job.enable: true
  security.recordOperateLog: true
  dbs:
    - datasource:
        # need to replace datasource
        name: english_datasource
        url: ${MYSQL_EN_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=${MYSQL_EN_TZ}
        username: ${MYSQL_EN_USERNAME}
        password: ${MYSQL_EN_PASSWORD}
      jpa:
        show-sql: true
        generate-ddl: true
        open-in-view: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: mysql
      scanPackages: com.vesoft.onewebsite.en.model
magic-api:
  web: /magic/web
# need to replace
#  resource.location: /Users/rivery/Desktop/projects/new-website/magic-scripts
  resource.location: /opt/metadata/magic-api
  show-url: false
  show-sql: true #配置打印SQL
  response-code:
    success: 0 #执行成功的code值
    invalid: 1 #参数验证未通过的code值
    exception: -1 #执行出现异常的code值
  page:
    size: pageSize # 页大小的请求参数名称 缺省时为size
    page: page # 页码的请求参数名称 缺省时为page
    default-page: 1 # 自定义默认首页 缺省时为1
    default-size: 10 # 自定义为默认页大小 缺省时为10
spring:
  datasource:
    # url: jdbc:mysql://192.168.8.44:3306/website?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: ${MYSQL_CN_URL}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=${MYSQL_CN_TZ}
    username: ${MYSQL_CN_USERNAME}
    password: ${MYSQL_CN_PASSWORD}
# need to replace datasource
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  mail:
    username: cloud-support@vesoft.com
    port: 587
    host: smtp.office365.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.starttls.enable: true
#      mail.smtp.ssl.auth: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.required: true
server:
  compression:
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
    enabled: true
  error:
    includeException: true
    includeStacktrace: ALWAYS
    includeMessage: ALWAYS